### ISSUE TITLE
Name of DAO

### ISSUE THREAD

**Issue by agelesspartners** [cure-dao/draft-whitepaper#37]
I'd like us to discuss the name of the DAO. If we can all purpose our suggested names and we can take a vote. It would be preferred if the DAO creates an entirely new brand rather than having something like AgelessDAO or dCures, etc. However, I'm open to suggestions.

Here are my suggestion (I'll update you with more suggestions later):

Skyline Health

Skyline

Thanks!

# Shortlist 
- dCures 
- MediDAO 
- CuraDAO 
- OmicDAO 
- OmicsDAO
https://www.rankedchoices.com/create

**Comment by mikepsinn** [comment]
Thanks, @agelesspartners !  @viznov @vincenzodomina @Taliskermalt  

Do you think we should vote to switch to a temporary name while we're trying to recruit working group members to contribute and provide feedback on the whitepaper? And then vote on a permanent name later?

Or should we keep Anonymous DAO until the whitepaper is complete and all working group teams are recruited?

**Comment by agelesspartners** [comment]
I'm open to either path. We can switch to Skyline as a temporary name until we finalize the working groups to vote if you'd like.

**Comment by vincenzodomina** [comment]
My suggestions for a temporary project name:

HumanDataDAO
HealthDataDAO
OpenHealthDAO
OpenHumanDAO
HumanDAO
InsilicoHumanDAO

**Comment by mikepsinn** [comment]
I like these short ones because it seems like the most successful websites have 2 syllables (google, amazon, VitaDAO, eBay)
dCures (ie. decentralized cures like dApp stands for decentralized app)
MediDAO

**Comment by vincenzodomina** [comment]
Let's do it like this:
- 1st round: Everyone proposes 5 names (out of the mentioned or new ones until Thursday) (or not)
- 2nd round: Out of all mentioned ones everyone picks 3 favorites -> first selection
- 3rd round: Out of the first selection everyone picks one favorite -> second selection
- 4th round: Out of the second selection everyone picks one favorite -> most voted one wins
Each round the day after for some thinking time.

Agree?

**Comment by mikepsinn** [comment]
@vincenzodomina That's a clever way to do it. It's kind of like rank choice voting but spread out over days. What's that method called or did you make it up?

Do you think it produces better results than regular rank choice voting?  

It seems like we might eventually want to tie rank choice voting to smart contracts, so I was looking around at some open-source voting tools. (The real reason was that I was trying to avoid working on the whitepaper.  I believe our focus on this issue is what's known as [bike-shedding](https://en.wiktionary.org/wiki/bikeshedding).)

I found a cool open-source rank choice voter:
https://github.com/davidmoritz/rcv
https://www.rankedchoices.com/vote#dao_name

Here's another interesting "this or that" method that would work well for a few choices. However,  it's way too slow for lots of choices.  I was answering for a while but the results still didn't converge to reflect my preferences. (You can click to see the current results at any time at the top)
https://github.com/coignetp/whatsbest
https://whatsbest.herokuapp.com/#/mash/3a49c7b0

**Comment by mikepsinn** [comment]
Also, I propose the following requirements for submission:

### Name Criteria

- Ideally no more than 3 syllables (like google, ebay, amazon). DAO is one syllable.
- .org domain must be available (unless the domain owner is willing to transfer ownership to the DAO). Check here: 
  [domains.google](https://domains.google) before submitting.
- Cannot be trademarked (unless the trademark owner is willing to cease and desist usage and transfer sole ownership of all logos, web properties, social media accounts, etc. to the DAO). Check here: [trademark-search.marcaria.com](https://trademark-search.marcaria.com)  before submitting.

And since we have AgelessDAO, dCures on the list, I get to propose `QuantimoDAO`.

This is my proposal for the permanent name, tagline, token name, and logo. 
The permanent name, tagline, token name, and logo for the DAO will be determined using the following method:
1. **Google Ads Conversion Rate** - The click rate and conversion rate for all combinations of names and taglines and logos will be determined using Google Ads. (The click rate is the percentage of people that click on the ad. The conversion rate is the percentage of people that both click on the ad and take an action, like sign up for our newsletter.)
2. **Rank Choice Voting** - The list of options will be provided to DAO members along with the Google Ads conversion rates. DAO members will then rank the options in order of preference. However, these marketing appeal metrics should be considered in their decision.

**Comment by vincenzodomina** [comment]
Excellent Mike! 

Yes i came up with that, sure i read it some where but couldn't think of a regular system. 
We can use what ever, just making proposals, but we should do it within a week to move on.

Updated the list of names above

**Comment by agelesspartners** [comment]
Thanks for all your input. I agree on the naming criteria. We should post our updated suggestions that adhere to these guidelines. Thanks.

**Comment by mikepsinn** [comment]
Sure!  Also, I was just joking about QuAnTiMoDAO.  (Although, I do love how you only have to add an A to it.)  

Also, I was thinking about the scope of the project and how there are so many components.  It's going to require lots of businesses and organizations as components.  These are probably also going to include other DAOs.  If DAOs replace all traditional corporations as I think they should, it would eventually become a DAO of DAO's. 

So I was kind of looking into sub-governance and saw an interesting "Pod Governance" protocol: 
https://www.orcaprotocol.org/

Not sure if or how soon something like that will be needed, but you guys might want to check it out.

**Comment by kevinperrott** [comment]
Hi all, 

I would suggest OpenCuresDAO, but solely because I think doing so minimizes time to the development of interventions, and because according to my understanding the DAO will already own it.

It has always been my intention to tokenize OpenCures and bring in the wisdom of the suffering crowds to direct its value.  There is some details to go over, but I will be putting **100% of OpenCures equity**, current investments and operating assets, into the DAO, which would then become the effective "owner" of OpenCures and all of its assets including tradenames, trademarks etc.   

I think it's pretty obviously a great brand... more than a few marketing gurus, including Anil Sethi former Director of Apple Health, have told me so... and if I gave it to the DAO it would really give it a chance to breathe...  Thoughts?

**Comment by kevinperrott** [comment]
I think I may have jumped the gun when I posted that OpenCuresDAO may be useful from a branding perspective.   I will leave that as an option but will recast it just as an offer without any apriori assumptions of commitments or involvement as the structure for such is still being developed.   More generally, in my experience the best results are found when an entity name represents the purpose of the entity and resonates with the people who would support it.  It is also true that finding a name that everyone likes is not always possible, in which case finding a name that everyone hates the least is usually a reasonable option.

**Comment by agelesspartners** [comment]
Kevin,

Thanks for the input. Yes, I believe finding a name that everyone hates the least is a reasonable option as well. We have created a list that has our top picks that we can then vote on. For names like OpenCuresDAO, AgelessDAO, QuantimodoDAO, etc. I believe they are definitely interrelated to our other project spaces that we have going. Our thinking is to create an entirely new brand that underpins the high-level mission & ideologies of all of our entities joining together as well as the mission of the DAO. Let me know your thoughts or if anyone else wants to comment feel free. Thanks!

**Comment by kevinperrott** [comment]
I have no further thoughts at the moment on the name of the DAO.   Saving lives and reducing suffering in the shortest amount of time is the only thing I care about and look forward to hearing discussions that are grounded in that awareness.
